# Generated by Django 3.0.3 on 2020-04-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malurl',
            name='url',
            field=models.URLField(max_length=120),
        ),
    ]
